#!/bin/bash

#xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

#xsnow -delay 30 -snowflakes 200 -ssnowdepth 100 -wsnowdepth 30 -norudolf -nosanta -notrees &
#xsnow -delay 30 -snowflakes 200 -nokeepsnowonwindows -nokeepsnowonscreen -norudolf -nosanta -notrees &

xsct 2000 &
sxhkd &
nitrogen --restore &
slstatus &
picom --shadow --shadow-radius 13 --shadow-opacity 0.69 --shadow-color "#000000" --fading --vsync &
pulseaudio --start &
exec dbus-run-session dwm
